# Generated by Django 3.2 on 2021-08-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210826_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='accredit',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
