# Generated by Django 3.2 on 2021-08-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_accredit_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='sia_exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
