# Generated by Django 3.2 on 2021-08-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_worker_sia_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredit',
            name='bib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.bib'),
        ),
    ]
