# Generated by Django 3.2 on 2021-08-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_accredit_bib'),
    ]

    operations = [
        migrations.AddField(
            model_name='accredit',
            name='wristband',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='event.wristband'),
            preserve_default=False,
        ),
    ]
