# Generated by Django 3.2 on 2021-09-13 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0007_accredit_wristband'),
    ]

    operations = [
        migrations.AddField(
            model_name='accredit',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accredit',
            name='dateEntered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accredit',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='dateEntered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accredit',
            name='transport_home',
            field=models.CharField(choices=[(None, 'Please select tranport'), ('Company', 'Showsec Provided Transport'), ('Public', 'Public Transport'), ('Private', 'Private Transport')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
