# Generated by Django 3.2 on 2021-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20210913_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='accredit',
            name='firstIdChecked',
            field=models.CharField(choices=[(None, 'Please Select ID'), ('SIA', 'SIA Licence'), ('Driver', 'Drivers Licence'), ('Passport', 'Passport'), ('StaffIDCard', 'Approved Staff ID Card'), ('PASS', 'Pass Scheme Card')], default='SIA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accredit',
            name='secondIdChecked',
            field=models.CharField(choices=[(None, 'Please Select ID'), ('SIA', 'SIA Licence'), ('Driver', 'Drivers Licence'), ('Passport', 'Passport'), ('StaffIDCard', 'Approved Staff ID Card'), ('PASS', 'Pass Scheme Card')], default='SIA', max_length=50),
            preserve_default=False,
        ),
    ]
