# Generated by Django 3.2 on 2021-09-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20210913_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredit',
            name='transport_home',
            field=models.CharField(choices=[(None, 'Please select transport'), ('Company', 'Company Provided Transport'), ('Public', 'Public Transport'), ('Private', 'Private Transport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='accredit',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='event.worker'),
        ),
    ]
