# Generated by Django 3.2 on 2021-09-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_accredit_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bib',
            name='image',
        ),
    ]
