# Generated by Django 3.2 on 2021-09-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20210923_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredit',
            name='tent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.tent'),
        ),
    ]
