# Generated by Django 3.2 on 2021-10-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20210928_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='C:\\Users\\Niel\\Documents\\Programming\\festival2\\src\\media\\avatar.png', upload_to='photo/event')),
                ('is_active', models.BooleanField(default=True)),
                ('accredit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.accredit')),
            ],
        ),
    ]
