# Generated by Django 3.2 on 2021-10-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_workerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerimage',
            name='image',
            field=models.ImageField(default='C:\\Users\\Niel\\Documents\\Programming\\festival2\\src\\media\\avatar.png', upload_to='photo/<function WorkerImage.uploadLocation at 0x04A5E8A0>'),
        ),
    ]
