# Generated by Django 3.2 on 2021-10-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_workerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerimage',
            name='image',
            field=models.ImageField(default="C:\\Users\\O'Niel Richards\\Documents\\workspace\\festival2\\media/avatar.png", upload_to='photo/<function upload_location at 0x04A98780>'),
        ),
    ]
