# Generated by Django 3.2 on 2021-10-20 18:42

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_workerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerimage',
            name='image',
            field=models.ImageField(default="C:\\Users\\O'Niel Richards\\Documents\\workspace\\festival2\\src\\media\\avatar.png", upload_to=event.models.upload_location),
        ),
    ]
