# Generated by Django 3.2 on 2021-11-03 21:14

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_workerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerimage',
            name='image',
            field=models.ImageField(default='C:\\Users\\Niel\\Documents\\Programming\\festival2\\src\\media\\avatar.png', upload_to=event.models.upload_location),
        ),
    ]
