# Generated by Django 3.2 on 2021-11-03 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0021_alter_workerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logistic_staff',
            field=models.ManyToManyField(related_name='authorised_for_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
