# Generated by Django 3.2 on 2021-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_company_name'),
        ('event', '0022_alter_event_logistic_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='suppliers',
            field=models.ManyToManyField(related_name='supplies_for_event', to='supplier.Company'),
        ),
    ]
