# Generated by Django 3.2 on 2021-11-13 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0002_alter_company_name'),
        ('event', '0023_alter_event_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='payroll_id',
            field=models.CharField(default='GOV000', max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='logistic_staff',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='authorised_for_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='suppliers',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='supplies_for_event', to='supplier.Company'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='supplier.company'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='working_at',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.CreateModel(
            name='BulkInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffCSVFile', models.FileField(upload_to='')),
                ('dateEntered', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='supplier.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
