# Generated by Django 3.2 on 2021-11-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20211113_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkinsert',
            old_name='user',
            new_name='uploaded_by_user',
        ),
    ]
