# Generated by Django 3.2 on 2021-11-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_rename_user_bulkinsert_uploaded_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkinsert',
            name='staffCSVFile',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
