# Generated by Django 3.2 on 2021-11-15 18:01

from django.conf import settings
from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0026_alter_bulkinsert_staffcsvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logistic_staff',
            field=models.ManyToManyField(related_name='authorised_for_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='suppliers',
            field=models.ManyToManyField(related_name='supplies_for_event', to='supplier.Company'),
        ),
        migrations.AlterField(
            model_name='workerimage',
            name='image',
            field=models.ImageField(default="C:\\Users\\O'Niel Richards\\Documents\\workspace\\festival2\\src\\media\\avatar.png", upload_to=event.models.upload_location),
        ),
    ]
