# Generated by Django 3.2 on 2021-12-05 01:46

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_worker_sia_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredit',
            name='camping',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workerimage',
            name='image',
            field=models.ImageField(default="C:\\Users\\O'Niel Richards\\Documents\\workspace\\festival_accreditation\\src\\media\\avatar.png", upload_to=event.models.upload_location),
        ),
    ]
