# Generated by Django 3.2 on 2021-12-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_alter_accredit_camping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredit',
            name='camping',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
