# Generated by Django 3.2 on 2022-07-12 22:20

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_alter_accredit_camping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerimage',
            name='image',
            field=models.ImageField(default='C:\\Users\\richa\\OneDrive\\Documents\\GitHub\\festival_accreditation\\src\\media\\avatar.png', upload_to=event.models.upload_location),
        ),
    ]
